### ISSUE TITLE
Dashboard Widget

### ISSUE THREAD

**Issue by strarsis** [Strategy11/formidable-forms#102]
It would be nice if a Dashboard Widget is added so one can see at one glance what 
the last records are, unread records, and so on.

**Comment by strarsis** [comment]
@Crabcyborg: So this is a bad idea/proposal then?

**Comment by Crabcyborg** [comment]
> @Crabcyborg: So this is a bad idea/proposal then?

@strarsis sorry for just closing this without much explanation!

This just isn't where we really collect our issues, and this is a feature request. We generally don't track feature requests as issues in the first place.

If you want to make a feature request, I believe we suggest contacting support directly.

**Comment by strarsis** [comment]
@Crabcyborg: Is `views` a Formidable-specific feature?

**Comment by Crabcyborg** [comment]
> @Crabcyborg: Is `views` a Formidable-specific feature?

@strarsis yes, I think Formidable is the only form builder plugin that offers a full framework for displaying data.

https://formidableforms.com/knowledgebase/create-a-view/

This is a premium feature of formidable, so it isn't included with the free plugin.

But I think the functionality is here that you could easily set up a page yourself that showed all of the details you listed, and a whole lot more.
