### ISSUE TITLE
Formidable Forms File Possible Security Threat by Quttera scan

### ISSUE THREAD

**Issue by chromechris** [Strategy11/formidable-forms#1024]
![Screenshot 2023-01-06 123618](https://user-images.githubusercontent.com/16638698/211086575-812cc18c-0917-4182-92dd-e83a4cf0aac8.jpg)

**Comment by Crabcyborg** [comment]
Hi @chromechris, thank you for reporting your concern!

That's just one of our SVG files.

![upgrade-rocket](https://user-images.githubusercontent.com/9134515/211088216-2fefd740-ff72-4548-9bbd-300783342141.svg)

It may be best to double check your file matches ours in case it was hacked, but I believe this is just a false positive.  I checked the file on our end to confirm and it's just a lot of path data. If they're looking for obfuscated JavaScript using regex, it likely just mistook our path data for obfuscated JavaScript.

I'm going to close this as I don't think this should require any changes on our end.

**Comment by chromechris** [comment]
Ah, ok, thank you @Crabcyborg
