### ISSUE TITLE
Wrong "updates available" number

### ISSUE THREAD

**Issue by drmab** [Strategy11/formidable-forms#103]
Ever since I updated to the latest version (3.04.03), the number of plugin with updates available is off by almost 20. If I deactivate Formidable Forms, it goes back to the real number. 

Tested on WP 4.9.8, 4.9.9, 5.0.0 and 5.0.2

Also, happy new year!

**Comment by srwells** [comment]
Thanks! we are aware of the issue, and we are working on a fix to get that update number correct.

**Comment by stephywells** [comment]
Hi there, This has already been fixed. You can find the commit here:
https://github.com/Strategy11/formidable-forms/commit/ea743ba2f6beee5805de00c7c11dbc5247b29317

For support questions, be sure to open a support ticket. Thanks!
