### ISSUE TITLE
Broken Print Styles

### ISSUE THREAD

**Issue by jeremylind** [Strategy11/formidable-forms#1077]
https://github.com/Strategy11/formidable-forms/commit/a9186a69c7c3462f3caeefab2925f83a1b5de586 removes the `frm_page_container` class from the `classes/views/frm-entries/show.php` view. Removing this class breaks print styles that align the sidebar content to the bottom of the page when printing.

**Comment by jeremylind** [comment]
Beautiful! Thank you for the quick fix.

**Comment by stephywells** [comment]
Thanks for the report @jeremylind ! We appreciate it!
