### ISSUE TITLE
put duplicated field behind source field please

### ISSUE THREAD

**Issue by nicmare** [Strategy11/formidable-forms#11]
dear frm team, 
when i have a complex form with a lot of fields then it is annoying to duplicate a field in the middle of the form and it will appear at the end of the form. i then have to drag and drop it to where it should be. i know. its a tiny feature and a minor important request. but i would really appreciate it :D

**Comment by stephywells** [comment]
We are planning on adding a dropdown to the duplicate option to choose whether it goes to to end or right after the field to duplicate. Can you vote here?
https://formidablepro.com/help-desk/duplicate-fields-in-place/

We are tracking this topic in our private repo:
https://github.com/Strategy11/formidable/issues/63
