### ISSUE TITLE
Upgraded to 2.0.11 and formidable function getAll not giving proper results

### ISSUE THREAD

**Issue by SurekhaRane** [Strategy11/formidable-forms#12]
What needs to be passed to getAll function to get all the meta data from the frm_items_meta table?

We have a field in form fields table and the id of it is present in items meta table.

Using getAll function we trying to pick the meta vale from items meta table based on the field key and not the field id. If we try to print the result then we are not getting data based on the field key but instead using field id.
This was working with the older version but stopped working for version 2.0.11.

Can you please help us with this?

**Comment by stephywells** [comment]
We've added a hook for this. Can you see this related topic and post in the help desk for support?
https://formidablepro.com/help-desk/frmentrygetone-key-true-no-longer-returns-field-keys-in-2-0/
