### ISSUE TITLE
Error message not displayed when input[type="file"] exists in the form

### ISSUE THREAD

**Issue by Tes3awy** [Strategy11/formidable-forms#123]
I have a form that has an `input[type="file"]` inside. (Please see screenshot below).

![FireShot Capture 036 - Contact us - TED's - teds 34way com](https://user-images.githubusercontent.com/11368432/61176432-29332680-a5c1-11e9-9c99-df969e0656ad.jpg)

If I submit an empty form, I get error labels beneath the form `input[type="text"]`, `input[type="email"]`, and `input[type="tel"]` only but not for the `input[type="file"]`. Also, The error message that is supposedly previewed above the form is not there. (Please see screenshot below) 

![FireShot Capture 037 - Contact us - TED's - teds 34way com](https://user-images.githubusercontent.com/11368432/61176468-a2327e00-a5c1-11e9-96e0-41ac8bf0444b.jpg)

> Update: the div that should have the error within is empty. In my case, that div is as follows: `<div class="frm_error" id="frm_error_field_13"></div>` 
![Screenshot_2019-07-13_23-02-35](https://user-images.githubusercontent.com/11368432/61176512-64822500-a5c2-11e9-9937-f322c9266314.png)

Is that a bug or just the standard way FF deals with `input[type="file"]`?. Thank you!

**Development Environment:**
WordPress: 5.2.2
FF: 4.01.02
FF Pro: 4.01.02
PHP Version: 7.3.x

**Comment by srwells** [comment]
I am unable to replicate this in my test. Can you export your form as an XML file, then compress/zip it and attach it here for further testing?

**Comment by stephywells** [comment]
Since we don't provide support here, I'll go ahead and close this. Please open a support ticket so we can help. Thanks!
