### ISSUE TITLE
Make default phone format customizable

### ISSUE THREAD

**Issue by sbuchali** [Strategy11/formidable-forms#137]
Just wondering why german phone numbers cause error messages even if they get typed the right way (e.g. `(01234) 5678-90` or `01234 / 678-90`).

That's because https://github.com/Strategy11/formidable-forms/blob/master/classes/models/FrmEntryValidate.php always sets a default format, which seems to be an american-only:

```php
/**
 * @since 3.01
 */
private static function default_phone_format() {
	return '^((\+\d{1,3}(-|.| )?\(?\d\)?(-| |.)?\d{1,5})|(\(?\d{2,6}\)?))(-|.| )?(\d{3,4})(-|.| )?(\d{4})(( x| ext)\d{1,5}){0,1}$';
}
```

So the only way to get around this seems to be that one needs to set an individual pattern for every phone field in every form.  
Or to manually adapt in within the code, making plugin upgrades break.

Why is there a phone number format required? W3C does not explicitly require one, btw.

So can it be made optional or configurable in a global way?

**Comment by Crabcyborg** [comment]
Hi @sbuchali.

Sorry for getting back to you after so much time. This isn't our usual support channel.

For free support, our main channel is through WordPress.org at https://wordpress.org/support/plugin/formidable/

I took a look into your issue.

We already have a hook in place for controlling the phone format for all fields without the need to update fields individually. This hook is just currently undocumented, but we're working on adding documentation soon.

The filter is `frm_phone_pattern`.

To make the phone number validation optional in a global way, you can use this snippet which makes the phone pattern more inclusive so it can accept any input.
```
add_filter(
	'frm_phone_pattern',
	function() {
		$pattern = '^.*$';
		return $pattern;
	}
);
```

**Comment by sbuchali** [comment]
Thanks a lot! We will try!
