### ISSUE TITLE
Error with Formidable Forms Plugin on WordPress 6.4.1

### ISSUE THREAD

**Issue by elhaddajiOtmane** [Strategy11/formidable-forms#1405]
### Description:
After updating to WordPress 6.4.1, an error occurred with the Formidable Forms plugin. The site experiences issues, and the WordPress recovery mode was suggested.

### Steps to Reproduce:
1. Update WordPress to version 6.4.1.
2. Navigate to [Formidable Forms Welcome Page](https://iaweb.dev/wp-admin/admin.php?page=formidable-welcome).
3. Observe the error.

### Expected Behavior:
The Formidable Forms plugin should function without causing any errors.

### Actual Behavior:
An E_ERROR type error occurs in FrmAddonsController.php on line 1260, preventing normal plugin functionality.

### Environment:
- WordPress version: 6.4.1
- Theme: Haptic Child
- Plugin: Formidable Forms (version 6.6)
- PHP version: 8.0.30

### Error Details:
```
======================
Une erreur de type E_ERROR a été causée dans la ligne 1260 du fichier /var/www/vhosts/iaweb.dev/httpdocs/wp-content/plugins/formidable/classes/controllers/FrmAddonsController.php. Message d’erreur : Uncaught TypeError: Cannot access offset of type string on string in /var/www/vhosts/iaweb.dev/httpdocs/wp-content/plugins/formidable/classes/controllers/FrmAddonsController.php:1260
Stack trace:
#0 /var/www/vhosts/iaweb.dev/httpdocs/wp-content/plugins/formidable/classes/controllers/FrmWelcomeController.php(175): FrmAddonsController::conditional_action_button()
#1 /var/www/vhosts/iaweb.dev/httpdocs/wp-content/plugins/formidable/classes/views/welcome/show.php(90): FrmWelcomeController::maybe_show_conditional_action_button()
#2 /var/www/vhosts/iaweb.dev/httpdocs/wp-content/plugins/formidable/classes/controllers/FrmWelcomeController.php(102): include('...')
#3 /var/www/vhosts/iaweb.dev/httpdocs/wp-includes/class-wp-hook.php(324): FrmWelcomeController::screen_content()
#4 /var/www/vhosts/iaweb.dev/httpdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#5 /var/www/vhosts/iaweb.dev/httpdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#6 /var/www/vhosts/iaweb.dev/httpdocs/wp-admin/admin.php(259): do_action()
#7 {main}
  thrown
```

**Comment by Crabcyborg** [comment]
Thank you for reporting this issue @elhaddajiOtmane

We normally suggest using our WordPress support for issues in our Lite plugin https://wordpress.org/support/plugin/formidable/

But I looked into this and I was able to replicate your error, and I made a small update for next release (https://github.com/Strategy11/formidable-forms/pull/1406).

This issue will close once that pull request is merged, which I will do after I make this comment.

Thank you for using Formidable!
