### ISSUE TITLE
Error when importing an xml file containing several exported form

### ISSUE THREAD

**Issue by rija** [Strategy11/formidable-forms#16]
Hi,

I've exported four forms from an installation of Wordpress that runs Formidable Forms Free (2.0.15) into one xml file. 

When I imported the XML file into another installation with the same version of Formidable Forms, I had the following error:

WP_Error Object ( [errors:WP_Error:private] => Array ( [SimpleXML_parse_error] => Array ( [0] => There was an error when reading this XML file ) ) [error_data:WP_Error:private] => Array ( [SimpleXML_parse_error] => Array ( [0] => LibXMLError Object ( [level] => 3 [code] => 64 [column] => 6 [message] => XML declaration allowed only at the start of the document [file] => [line] => 4 ) ) ) )

I fixed it by removing extra lines at the top of the XML file, but I thought I'd let you know.

**Comment by stephywells** [comment]
This is actually a conflict with your theme or another plugin. The whitespace at the top of the file is being output everywhere. I'd recommend tracking down the source of the conflict so it can be resolved.

**Comment by BrianTolman** [comment]
Or, just open the XML File in an editor, and remove all the blank lines....

... or at least that is what worked for me
