### ISSUE TITLE
Filter args are not passed to frm_trigger_create_action

### ISSUE THREAD

**Issue by andrewklimek** [Strategy11/formidable-forms#1881]
I assume this is a mistake, and the filter is supposed to receive the `$filter_args` variable so that it has access to `entry_id` and `form_id`

https://github.com/Strategy11/formidable-forms/blob/83f2ae0c8133cb775eb9512698ddfdaeffaeeb47/classes/controllers/FrmFormActionsController.php#L474-L482

**Comment by Crabcyborg** [comment]
Thank you for reporting this @andrewklimek!

I can confirm that looks wrong.

This is old code. It looks like it hasn't been touched in 8 years, so it's likely a very old issue.

Fixed with https://github.com/Strategy11/formidable-forms/pull/1882

**Comment by Crabcyborg** [comment]
@andrewklimek Yeah, I'm not sure if it was happening another way. I know the draft actions do get triggered.

Hopefully this doesn't actually introduce any issues with it possibly happening twice?

**Comment by andrewklimek** [comment]
@Crabcyborg I haven't tested it actually, but it looks like that whole function wouldn't even run.
It is hooked to `frm_trigger_create_action`
...but `FrmProEntriesController::remove_draft_hooks` is hooked to `frm_after_create_entry` priority 1 and that function removes `trigger_create_actions` from `frm_after_create_entry`

Pasting relevant code below:

```
add_action( 'frm_after_create_entry', 'FrmProEntriesController::remove_draft_hooks', 1 );
add_filter( 'frm_trigger_create_action', 'FrmProFormActionsController::maybe_trigger_draft_actions', 10, 2 );

public static function remove_draft_hooks( $entry_id ) {
	if ( ! FrmProEntry::is_draft( $entry_id ) ) {
		return;
	}

	// don't let sub entries remove these hooks
	$entry = FrmEntry::getOne( $entry_id );
	if ( $entry->parent_item_id ) {
		return;
	}

	//remove hooks if saving as draft
	remove_action( 'frm_after_create_entry', 'FrmProEntriesController::set_cookie', 20 );
	remove_action( 'frm_after_create_entry', 'FrmFormActionsController::trigger_create_actions', 20 );
	add_action( 'frm_after_create_entry', 'FrmProFormActionsController::trigger_draft_actions', 10, 2 );

	// trigger after draft save hook
	do_action( 'frm_after_draft_entry_processed', array( 'entry_id' => $entry_id, 'form' => $entry->form_id ) );
}

public static function maybe_trigger_draft_actions( $event, $args ) {
	if ( isset( $args['entry_id'] ) && FrmProEntry::is_draft( $args['entry_id'] ) ) {
		$event = 'draft';
	}
	return $event;
}
```
