### ISSUE TITLE
[function get_localized_date()] time zone is not reflected.

### ISSUE THREAD

**Issue by tomoPola** [Strategy11/formidable-forms#2190]
https://github.com/Strategy11/formidable-forms/blob/200c761ccdf4ed0f949ba718ef311caefa9e138e/classes/helpers/FrmAppHelper.php#L2730C10-L2730C19

I have set the WordPress timezone to “Tokyo”, but the dates of Formidable forms records are recorded in UTC.
It seems that the ``date_i18n()`` function is deprecated and can't get the date in the correct time zone set in Wordpress.
Please modify ``date_i18n()'' to ``wp_date()''.
Thank you in advance.

**Comment by Crabcyborg** [comment]
@tomoPola

I don't see any deprecated messages related to `date_i18n`. Do you have a source for that?

Our `get_localized_date` function begins with a call to `get_date_from_gmt`, which handles the timezone conversion.

Dates are always stored in UTC, but displayed in the localized format. Database results should always be in UTC, regardless of server timezone.

I don't believe there is an issue here, so I'm going to close this issue. If you have any other questions, feel free to respond back, though this isn't our dedicated support channel. You should generally reach out at https://wordpress.org/support/plugin/formidable/ or https://formidableforms.com/new-topic/ if you have an active license and you're experiencing issues with a Pro feature.

Thank you!
