### ISSUE TITLE
Unique field on number input

### ISSUE THREAD

**Issue by justinmz** [Strategy11/formidable-forms#25]
Hi Guys,

I think there's a bug when selecting a number input as unique. It works fine for me with email or text but not with number.

Thanks
Justin

**Comment by justinmz** [comment]
There seems to be a bigger problem here, if you use a text input and mark it unique and use numbers in that field it ignores the unique setting.

**Comment by jwahlin** [comment]
Do you still have this problem? I'm wondering if it was fixed by another commit a while back.

**Comment by justinmz** [comment]
Happy to close this for now, we ended up cleaning out the duplicated manually for our submissions as it was a short 3 day campaign. Have not had a chance to test this again sorry.
