### ISSUE TITLE
[redis] cache_delete_group flushes complete wp network object cache!

### ISSUE THREAD

**Issue by svandragt** [Strategy11/formidable-forms#26]
https://github.com/Strategy11/formidable-forms/blob/master/classes/helpers/FrmAppHelper.php#L509-L511

Even though the intention is to delete a single row, the lines linked above flush the **complete Redis object cache of a WordPress Network!**. Because of this we cannot continue to use the plugin.

My colleague wrote a patch to fix caching issues in our infrastructure before we were aware of this issue that might be useful for yourselves as a potential start for a fix:

```php
/**
 * Formidable cache patch
 */
function wpc_formidable_patch() {
	wp_cache_add_non_persistent_groups( array(
		'frm_entry', 'frm_field', 'frm_form', 'frm_styles'
	) );
}
add_action( 'init', 'wpc_formidable_patch' );
```

**Comment by stephywells** [comment]
This has been fixed for the release this week. Here are the changes if you'd like them now.
https://github.com/Strategy11/formidable-forms/commit/c277a490d17f8ab8a6c5768fd9b89fd16170fa34

Thanks!
