### ISSUE TITLE
Using frm_form_error_class or frm_main_feedback with AJAX

### ISSUE THREAD

**Issue by tlygnersjo** [Strategy11/formidable-forms#28]
Hi,

I'm currently using both of the following hooks: frm_form_error_class and frm_main_feedback with form that is not posted through AJAX. But as soon as i activate AJAX for that form it stops working.

Is this a known problem or anything you can resolve?

**Comment by stephywells** [comment]
Can you please open a ticket in our help desk so our team can assist you with this?
https://formidablepro.com/new-topic/

Thanks!
