### ISSUE TITLE
Activation bug

### ISSUE THREAD

**Issue by lohic** [Strategy11/formidable-forms#5]
Hello,

I have an activation bug on formidable pro 2.0.03
I'm on wordpress 4.2 with PHP 5.5.23-1 and MySQL 5.5.5

Here are the two activation message error :
`Plugin could not be activated because it triggered a fatal error.`

`Fatal error: Class 'FrmHooksController' not found in /home/2/r/ralstonbau/www/wp-content/plugins/formidable/formidable.php on line 71`

**Comment by stephywells** [comment]
One other user had this problem, and I thought it was related to php 5.2. I just tested on 5.2 and it worked for me. Maybe you can provide admin access so I can take a look? Can you post privately in our help desk with info?
http://formidablepro.com/help-topics/

**Comment by lohic** [comment]
I just created a private topic on your help-topics with login/password

**Comment by lohic** [comment]
ok reuploaded the plugin and everything works fine, thank you very much

**Comment by srwells** [comment]
Glad that took care of it...We'll keep an eye on this to see if we can find the source of the issue.
