### ISSUE TITLE
Option to turn off Email Subject Title Encoding 

### ISSUE THREAD

**Issue by a3rev** [Strategy11/formidable-forms#7]
Hi Guys

We are the devs of the WP Email Template plugin https://wordpress.org/plugins/wp-email-template/

One of our Pro Version License holders who is also a Formidable Forms user has reported an issue 
https://a3rev.com/forums/topic/strage-url-link-showing-on-email-header/

- when using WP Email Template to apply a template to your emails when they pass through wp_mail the subject title is encoded. This is done with your plugin by this

`if ( apply_filters('frm_encode_subject', 1, $atts['subject'] ) ) {
            $atts['subject'] = '=?'. $charset .'?B?'. base64_encode($atts['subject']) .'?=';
        }`

We have released a maintenance upgrade with this filter that disables the subject title encoding

`frm_encode_subject`

I cannot be sure why you encode the email subject title - and what purpose that serves? But it would be very good if you either did not do that or added a setting to your plugin that allowed your users to turn that subject title encoding OFF.

Thank you - Steve

**Comment by stephywells** [comment]
The subject is encoded for UTF-8 characters. You can read more here:
http://ncona.com/2011/06/using-utf-8-characters-on-an-e-mail-subject/

With English-only sites, turning off the encoding will likely not make a difference. We've been considering adding an option for this, so I'll add it to our roadmap.
