### ISSUE TITLE
shortcode as shortcode attribute values has stopped rendering now

### ISSUE THREAD

**Issue by prasad230776** [Strategy11/formidable-forms#88]
previously using shortcodes inside another shortcode as their attribute values were rendering correctly before they were processed finally, but in recent versions, i found them not rendering if they were used as inline shortcodes in another shortcode and displaying as shortcodes themselves .. is there any tweak in order to make them work correctly by passing the rendering result of inner shortcodes for the outer ones.

**Comment by LauraSteiner** [comment]
Could you please ask your question in our helpdesk?
