### ISSUE TITLE
license question?

### ISSUE THREAD

**Issue by c0fe** [Strategy11/formidable-forms#931]
What is the license on this project?

**Comment by Crabcyborg** [comment]
Hi @c0fe sorry for the delay on reply, we don't usually track issues or do support here. Our WordPress support (https://wordpress.org/support/plugin/formidable/) is usually the main channel for asking questions about our lite plugin.

Our license information can be found in our plugin's main file. It's GPL version 2 https://github.com/Strategy11/formidable-forms/blob/572eec0586070ca880416339de8306973d2f6d33/formidable.php#L16

I'm going to go ahead and close this as well.

Have a good day!
